# Generated by Django 3.2.4 on 2021-11-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('avatar', models.ImageField(default='chicken.jpg', upload_to='avatars/')),
                ('info', models.TextField(default='N\\A', max_length=200)),
                ('username', models.CharField(default='#user', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('XP', models.IntegerField(default=0)),
                ('level', models.IntegerField(choices=[(0, 'Sleepy Baby'), (1, 'Basic Teen'), (2, 'Average Nerd'), (3, 'Script Kiddie'), (4, 'Hacker'), (5, 'Master')], default=0)),
                ('global_rank', models.IntegerField(default=0)),
                ('puzzles_completed', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('languages', models.TextField(default='N\\A', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
