# Generated by Django 3.2.4 on 2021-11-11 17:20

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('passingMarks', models.IntegerField(default=22)),
                ('endDate', models.DateTimeField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='interview_name')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(default='number', max_length=50)),
                ('marks', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('answer', models.CharField(default=0, max_length=50)),
                ('choice_a', models.CharField(default='a', max_length=200)),
                ('choice_b', models.CharField(default='b', max_length=200)),
                ('choice_c', models.CharField(default='c', max_length=200)),
                ('choice_d', models.CharField(default='d', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='description')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('marks', models.IntegerField(default=0)),
                ('correct', models.ManyToManyField(blank=True, related_name='Incorrect', to='main.AnswerQuestion')),
                ('incorrect', models.ManyToManyField(blank=True, related_name='Correct', to='main.AnswerQuestion')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interview')),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='questions',
            field=models.ManyToManyField(related_name='Questions', to='main.Question'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.question'),
        ),
    ]
